#!/bin/bash -eu

ROOT=$(cd $(dirname $0); pwd)
MYSQL_HOST_PORT=$(curl -s http://metadata/computeMetadata/v1/instance/attributes/MYSQL_HOST_PORT -H "Metadata-Flavor: Google")
BIND=":8000"

exec $ROOT/web/web -tmpdir=/tmp -static=$ROOT/web/static -views=$ROOT/web/views -db=$MYSQL_HOST_PORT -bind=$BIND
